### ISSUE TITLE
Support android before 4.4 is broken in 4.0.7

### ISSUE THREAD

**Issue by john-kolt** [jknack/handlebars.java#720]
I not found any information about android versions support.
I was surprised when my application crahed on supported device.
Version handlebars.java:4.0.6 works fine on androids before 4.4

I've updated from 4.0.6 to 4.0.7 and catch exception

```11-14 16:01:52.782 7211-7211/su.skat.client E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at com.github.jknack.handlebars.helper.DefaultHelperRegistry.<init>(DefaultHelperRegistry.java:73)
        at com.github.jknack.handlebars.Handlebars.<init>(Handlebars.java:270)
        at com.github.jknack.handlebars.Handlebars.<init>(Handlebars.java:365)
```
`StandardCharsets` appeared in Android 4.4:
https://developer.android.com/reference/java/nio/charset/StandardCharsets.html
